### ISSUE TITLE
KIM Integration - support update operation in transition phase

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/kyma-environment-broker#1068]
Support update operation  updating Runtime CR with appropriate values.

We have settings telling that given plan is managed by KIM only or is driven by provisioner (but Runtime CR is to be updated as well). 
Consider cases for both settings and different states of already provisioned clusters (i.e. KIM only driven plan, but cluster provisioned by provisioner, no Runtime CR present - migration not done yet).

**Notes**
- Some fields of Runtime CR are managed by SRE. See examples.
- In case provisioner is still used for given plan if either of paths fails (provisioner or KIM) - fail the operation

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/kyma-environment-broker/pull/1090/files
