### ISSUE TITLE
KIM Integration - double check that upgrade operation is done directly on Runtime CR

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/kyma-environment-broker#1072]
SRE is supposed to upgrade clusters by updating designated fields directly in Runtime CRs.

TBD: how we handle upgrade for instances provisioner driven, but with Runtime CR managed by KEB?

AC:
- [ ] we are 100% sure that upgrades 
- [ ] KEB does not overwrite this SRE managed fields (except when creating Runtime CR during provisioning/unsuspension)

**Comment by szwedm** [comment]
SRE is implementing Orchestration operator to handle cluster upgrades: https://github.tools.sap/kyma/backlog/issues/5865

**Comment by szwedm** [comment]
According to Benjamin from SRE, next clusters upgrade is planned for the end of Nov/the beginning of Dec. Orchestration operator should be ready by that time.
