### ISSUE TITLE
Support cf-br20, cf-br30, cf-ap30

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1139]
**Description**

We will enhance azure, azure_lite and gcp plans with new regions. Then we will refresh catalogs on ERS side for new BTP regions.

**Reason**

We will  support one BTP regions:
1) Brasil (São Paulo) cf-br20 - Azure
2) Brasil (São Paulo) cf-br30 - GCP
3) Australia (Sydney) cf-ap30 - GCP

**AC**
- [x] 0) no feature flag
- [x] 1) extend `azure`, `azure_lite` plans region list with: `brazilsouth (Brasil, São Paulo)`
- [x] 2) extend `gcp` plan region list with: `southamerica-east1 (Brasil, São Paulo)` and `australia-southeast1 (Australia, Sydney)`
- [x] 3) Adjust documentation in the Help Portal: - (@IwonaLanger )
   - [x] [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment#region*)
   - [x] [Regions for the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/regions-for-kyma-environment?version=Cloud)
- [x] 3) [Release note](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%20Runtime&Valid_as_Of=2024-03-25%3A2024-03-25&locale=en-US&version=Cloud) - (@IwonaLanger ); published [here](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma+Runtime&locale=en-US&version=Cloud&Valid_as_Of=2024-09-24:2024-09-24).

Regions must look like:
- `gcp`:
```
	"region": {
		"_enumDisplayName": {
			"asia-northeast2": "asia-northeast2 (Japan, Osaka)",
			"asia-south1": "asia-south1 (India, Mumbai)",
			"europe-west3": "europe-west3 (Europe, Frankfurt)",
			"me-central2": "me-central2 (KSA, Dammam)",
			"me-west1": "me-west1 (Israel, Tel Aviv)",
			"us-central1": "us-central1 (US Central, IA)",
			"southamerica-east1 (Brasil, São Paulo)",
			"australia-southeast1 (Australia, Sydney)"
		},
		"enum": [
			"europe-west3",
			"asia-south1",
			"us-central1",
			"me-central2",
			"asia-northeast2",
			"me-west1",
			"southamerica-east1",
			"australia-southeast1"
		],
		"minLength": 1,
		"type": "string"
	}
```
- `azure`, `azure_lite`:
```
	"region": {
		"_enumDisplayName": {
			"australiaeast": "australiaeast (Australia, Sydney)",
			"centralus": "centralus (US Central, IA)",
			"eastus": "eastus (US East, VA)",
			"japaneast": "japaneast (Japan, Tokyo)",
			"northeurope": "northeurope (Europe, Ireland)",
			"southeastasia": "southeastasia (Asia Pacific, Singapore)",
			"uksouth": "uksouth (UK South, London)",
			"westeurope": "westeurope (Europe, Netherlands)",
			"westus2": "westus2 (US West, WA)",
			"brazilsouth (Brasil, São Paulo)"
		},
		"enum": [
			"eastus",
			"centralus",
			"westus2",
			"uksouth",
			"northeurope",
			"westeurope",
			"japaneast",
			"southeastasia",
			"australiaeast",
			"brazilsouth",
		],
		"minLength": 1,
		"type": "string"
	}
```

**Comment by IwonaLanger** [comment]
Publication requests:
- What's New: https://jira.tools.sap/browse/NGPDOC-5056
- Core documentation: https://jira.tools.sap/browse/NGPDOC-5057
