### ISSUE TITLE
Migrate schema-migrator from control-plane

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1185]
**AC**
- [x] Move code from control-plane to KEB
- [x] Adjust imports in KEB repo that point to schema-migrator in control-plane
- [x] Remove gophers from CODEOWNERS in control-plane
- [x] Build the schema-migrator image on PR in KEB
- [x] Build the schema-migrator image in the KEB release workflow
- [x] Update the auto bump script to bump the schema-migrator image version in the release workflow + security file should contain that image too
- [x] Make sure Provisionier will be not affected (they still need this)
- [x] Update docs

**Comment by szwedm** [comment]
### Arrangements (1.10.24)
Currently, [Schema Migrator](https://github.com/kyma-project/control-plane/tree/868d3d02df5914b292fac702245fc169d14e7819/components/schema-migrator) is a component inside [control-plane](https://github.com/kyma-project/control-plane) repository and is available for an external usage. However, it should be a component only for [Kyma Environment Broker](https://github.com/kyma-project/kyma-environment-broker).

**Comment by szwedm** [comment]
Schema Migrator has been incorporated into Kyma Environment Broker. Closing.
