### ISSUE TITLE
SB: Implement Service Binding APIs with DB support for all OSB API operations

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1198]
Subtask of the EPIC: https://github.com/kyma-project/kyma-environment-broker/issues/284

**AC**
- [x] 1) implement db schema for storing and deleting service bindings https://github.com/kyma-project/kyma-environment-broker/pull/1213 
- [x] 2) use db layer in the API endpoints https://github.com/kyma-project/kyma-environment-broker/pull/1262, https://github.com/kyma-project/kyma-environment-broker/pull/1305
- [x] 3) up to 10 SBs allowed, the throw validation error about that fact @MarekMichali https://github.com/kyma-project/kyma-environment-broker/pull/1291
- [x] 4) encrypt/decrypt credentials (kubeconfig) https://github.com/kyma-project/kyma-environment-broker/pull/1213
- [x] 5) if SB expired, then remove this bindings from DB (probably job, idea to store deletionTimestamp when ttl from users comes) done in https://github.com/kyma-project/kyma-environment-broker/issues/1347
- [x] 6) If somethng new for users, update documentation

**Comment by piotrmiskiewicz** [comment]
According to OSB API spec - binding creation must be an idempotent operation. Second, third and next reqeust for the same instance/binding ID (with the same parameters) must return HTTP Ok

**Comment by PK85** [comment]
10.10.2024 - Summary from the meeting about using only token requests from SA from SKR and idempotent behaviour:

Legend:
**BindingID**: means: BindingId - InstanceID pair on KEB side

**Contract between Provisioning Service and KEB bindings:**
- [ ] 1) KEB bindings returns 201 or 200 if everythibng ok, then Provisioning Service persist binding on their side
- [ ] 2) KEB bindings returns 400, 409, 500 if something wrong happen and then  Provisioning Service DO NOT persist binding on their side, just pass error to the user

**KEB bindings implementation details:**
- [ ] 1) we return 201 when BindingID was not existing, and was created with success
- [ ] 2) we return 200 when BindingID WAS already existing, input parameters are the same and was created with success (in_progress,error is not success)
- [ ] 3) we return 400 when invalid input params provided
- [ ] 4) we return 409 when BindingID already exists but input params different
- [ ] 5) we return 500 if KEB itself is not able to finalize binding creation

**KEB implementation about handling biinding related resources, like ServiceAccount, ClusterRole, ClusterRoleBidning**
