### ISSUE TITLE
SB: Define final input parameters can user send when creating Service Binding (e.g. ttl creds expiration time: 3h), and result response from the binding

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1202]
Subtask of the EPIC: https://github.com/kyma-project/kyma-environment-broker/issues/284

**AC**
- [x] 1) document final Input params like `ttl` and `serviceAccount`: true/false
- [x] 2) document Service Bindning output
- [ ] 3) add a section explaining in details in the bindings doc what are the cons and pros of using ServiceAccount and Gardener's kubeconfig modes

**Comment by MarekMichali** [comment]
Looks like TTL was already defined here https://github.com/kyma-project/kyma-environment-broker/pull/1189

**Comment by MarekMichali** [comment]
We decided to change to service_account from token_request.
ExpirationSeconds won't be changed.

**Comment by MarekMichali** [comment]
Only service account will be used.
