### ISSUE TITLE
SB: Create Provisioning Service on staging and test Kyma creation and binding management

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1203]
Subtask of the EPIC: https://github.com/kyma-project/kyma-environment-broker/issues/284

**AC**
- [x] user Provisioning API Service to work with kyma instance and service bindings, check if contract is ok and everything works as expected:
    - [x] Test on staging - tested on staging manually (Oct 23: We wait for Zahi for his bugfixing)
    - [x] Test on canary
    - [x] Test on production

**Comment by KsaweryZietara** [comment]
Documentation on how to create Kyma Binding via cis Provisioning API: [#664](https://github.tools.sap/kyma/documentation/pull/664)
