### ISSUE TITLE
SB: Create e2e SKR test for all new service bindings capabilities

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1204]
Subtask of the EPIC: https://github.com/kyma-project/kyma-environment-broker/issues/284

**AC**
- [x] 1) one e2e SKR test calling KEB APis
  - [x] 1.1) https://github.com/kyma-project/kyma-environment-broker/issues/1239, [PR#1244](https://github.com/kyma-project/kyma-environment-broker/pull/1244) 
  - [x] 1.2) add GET and DELETE test for TOKEN+REQUEST ~~and GARDENER~~ (they must fail if GET has dummy response, and when DSELETE TOKEN_REQUEST previous kubeconfig must NOT work, ~~and for GARDENER it must still work~~) 
https://github.com/kyma-project/kyma-environment-broker/pull/1249
  - [x] 1.3) test validation for `expiration_seconds` with less than 10 min, and more than 2h. Must fail and check validation message.  https://github.com/kyma-project/kyma-environment-broker/pull/1261
  - [x] 1.4) Create 11 bidings, 11th must fail with proper validation message https://github.com/kyma-project/kyma-environment-broker/pull/1283
- [ ] 2) new type of e2e test (could be written in go, special for Mr Wojciech). 
  - [ ] 2.1) Setup: We have prepared subacout on staging with Provisioing Service instance and binding, 
  - [ ] 2.2) Setup: Kyma entitlement added for example to AWS plan
  - [ ] 2.3) New test, where provisioning API creates Kyma cluster + Service Bindings, we can still use KCP CLI tech users to validate some things, or show why it failed. Use the SB kubeconfig and reach Kyma instance.

**Comment by MarekMichali** [comment]
Part 2 about provisioning api was moved to #1341
