### ISSUE TITLE
Timeout for update operation

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/kyma-environment-broker#1230]
There are many timeouts defined for different steps and operations.
Some hard-wired in the code, some configurable.

For update operation we have timeout set to 40 minutes, which happens to be insufficient e.g. when `MachineType` is updated.

SRE suggests following approach as for `update`:

>Introduce configuration for this timeout value in the KEB code and helm chart, with default having 120m (2 hours).  
>SRE would like to specify overrides for this configuration per each KCP environment.`

- reconsider all timeouts involved during updating process (steps etc.)
- take into consideration that some paths of execution are relatively short (administrators) and some take a lot of time (MachineType)
- perhaps we need to prepare consistent approach for all timeouts used by KEB, create separate tickets - this ticket is focused on update operation.

**Comment by MarekMichali** [comment]
This is connected with https://github.com/kyma-project/kyma-environment-broker/issues/981

**Comment by MarekMichali** [comment]
In update operation:
-  `check` step has hardcoded 40 min
- `check_runtime_resource` has a configurable timeout through the `APP_PROVISIONER_RUNTIME_RESOURCE_STEP_TIMEOUT` key. 

Other update steps have no timeout
