### ISSUE TITLE
SB: User persistence from context

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#1348]
Persist user context in bindings table.

**AC**

- [x] extend bindings table with created_by https://github.com/kyma-project/kyma-environment-broker/pull/1311
- [x] If user comse in "origin" attribute rewrite "origin" to created_by bindings attribute
- [x] or in "email" and "origin" attribute then persist in bindings then rewrite "email" to created_by 
https://github.com/kyma-project/kyma-environment-broker/pull/1351
- [x] **think** about returning user in get binding API endpoint

**Comment by KsaweryZietara** [comment]
There is no need to return user in get endpoint, because CIS return users based on their database.
