### ISSUE TITLE
SB: Validate OSB Api Compliance - Test Creation

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#1352]
Create a test for OSB Api Compliance especially to check if all error codes are correct.

**AC**
- [x] check headers, query parameter, body
- [x] check for every endpoint

**AC from https://github.com/kyma-project/kyma-environment-broker/issues/284** - https://github.com/kyma-project/kyma-environment-broker/issues/284#issuecomment-2418846444 - **KEB bindings responses details:**
- [x] 1) we return 201 when BindingID was not existing, and was created with success
- [x] 2) we return 200 when BindingID WAS already existing, input parameters are the same and was created with success (in_progress,error is not success)
- [x] 3) we return 400 when invalid input params provided  [JP - question - including not existent InstanceID?] [MM - non existing instanceID = 404]
- [x] 4) we return 409 when BindingID already exists but input params different
- [x] 5) we return 500 if KEB itself is not able to finalize binding creation
- [x] 6) we return 200 on DELETE when bindings exists, [JP - question - 410 when does not exists?  - it seems that DELETE is not supposed to be idempotent] [MM - OSB says 410 if not exists]

**Comment by MarekMichali** [comment]
Scenario: 
- user creates a binding with id x
- binding x expires
- user wants to create binding x again. The previous one with the same id is expired, but is still in the database

From meeting 17.09.2024: We decided to return 400 if the expired binding is still in the DB

**Comment by ralikio** [comment]
Further *AC* from ...:

**Contract between Provisioning Service and KEB bindings:**
- [ ] 1) KEB bindings returns 201 or 200 if everything ok, then Provisioning Service persist binding on their side
- [ ] 2) KEB bindings returns 400, 409, 500 if something wrong happen and then Provisioning Service DO NOT persist binding on their side, just pass error to the user
