### ISSUE TITLE
Check in details how much time provisioning SKR takes

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1418]
**AC**
- [x] 1) check metrics, they looks not ok (showing too much minutes): avg(avg_over_time(kcp_keb_v2_provisioning_duration_minutes_sum{plan_id="$plan_id"}[$__range]))
- [ ] 2) document (here add comment) how much time given step takes

**Comment by MarekMichali** [comment]
Almost all steps take less than 1 second. The vast majority of the provisioning time is taken up by the `Check_RuntimeResource` step.
Shoot c19591b took 7 minutes 33 seconds and 30 ms to provision, with the `Check_RuntimeResource` step taking 7 minutes 32 seconds and 49 ms.
