### ISSUE TITLE
Trial Suspension Test is not Properly Synchronized

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#1434]
**Description**

Consider the following scenario that fails our trial suspension test:

- 04:03:32 GMT - test: Provisioning new SKR instance...
- 04:03:32 - KEB starts provisioning
- 04:10:02.815679318 - job pickups suspension for cleaning
- 04:10:02.824955229Z - KEB receives suspension
- 04:11:06.692509550Z - kubeconfig created
- 04:13:55 - KEB succeed provisioning and proceeds with suspension
- 04:14:04 GMT - test: Runtime status after provisioning - instance provisioned but tests still did not finish `provisionSKR` functions
- 04:14:04 GMT - test: fails on `1) "before all" hook: Ensure SKR Trial is provisioned for "should wait until Trial Cleanup CronJob triggers suspension"` - while indirectly calling for kubeconfig secret
- 04:14:06.239843129Z - second deprovisioning started
- 04:21:03.835776602Z - suspension finished
- 04:21:06.807873304Z second deprovisioning finished

**AC**
- [x] refactor test so that it does not uses provisionSKR but its custom version that does not loads the shoot

**Comment by MarekMichali** [comment]
PR https://github.com/kyma-project/kyma-environment-broker/pull/1526
