### ISSUE TITLE
Refactor bindings_envtest_test

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1468]
Problems:
 - the bindings_envtest_test runs slow
 - the setup of those tests are copied from the existing code which makes problems when the production code is being changed (for example change from gorilla mux to the standard lib).

AC:
- do we need env test? If not remove, if yes go with next points:
 - tests does not perform HTTP calls (which are handled by custom "in test defined" mux) - call endpoint method directly.
 - do not start envtest for unit tests, which does not require envtest
 - consider to move the test to internal/broker

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/kyma-environment-broker/pull/1567
