### ISSUE TITLE
Introduce SLOG in KEB

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1469]
The following [comment](https://github.com/kyma-project/kyma-environment-broker/issues/497#issuecomment-2049161710) lists all places where we import different log implementations. Change them to use slog implementation.

- consider to remove logs from storage layer
- talk with SRE if they still have alerts based on some logs from KEB

**Comment by KsaweryZietara** [comment]
SRE let us know that their alerts are based on standard and custom metrics. The expressions are built around them when evaluating.
