### ISSUE TITLE
Remove invocations of deprecated method: `workqueue.NewNamedRateLimitingQueue`

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#1504]
Method `workqueue.NewNamedRateLimitingQueue` we use in queue.go is marked deprecated.

> // Deprecated: Use NewRateLimitingQueueWithConfig instead.

**AC**
- [x] `NewRateLimitingQueueWithConfig` used instead

**Comment by MarekMichali** [comment]
PR: https://github.com/kyma-project/kyma-environment-broker/pull/1543
