### ISSUE TITLE
CCEE: KEB and HAP works with regional based subscriptions for openstack plan

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#151]
**Description**

Main Epic: https://github.com/kyma-project/kyma/issues/13159

We need to enhance our hyper-scaler account pool to work with projects (subscriptions) from CCEE, they are regional-based. In case of **openstack** plan when user selects given **region**, schema: 										
```
"region": {
	"enum": [
		"eu-de-1",
		"ap-sa-1"
	],
	"type": "string"
```
for example **"eu-de-1"** HAP needs to pick up a free subscription for that given region. Currently, HAP chooses any of the not used ones and can use **"ap-sa-1"** which will cause a failure in the Gardener where the region name and subscription do not match.

**Hyperscyler Subscription == CCEE Project. Decision is made that under one Project we can provision Kyma clusters for many customers (global account IDs)**

**Reasons**

Without that feature, KEB cannot support **openstack** plan with more than one region.

**AC**

- [x] 1) HAP works with a pool of subscriptions per region, only for **openstack** plan. All other plans still have one pool per plan.
   - [x] 1.1) Every region e.g: "eu-de-1" has its own pool, where KEB uses a round-robin strategy to get one. (It needs to work similar to Trial subscription support)
- [x] 2) Test on Dev environment that both regions work as expected

**Dependecy**

- check with SRE if subscriptions are provided in the gardener projects

**Comment by PK85** [comment]
@piotrmiskiewicz please organize a meeting with a team with some explanation about HAP and changes

**Comment by jaroslaw-pieszka** [comment]
Assumption made - we will create separate **providers** for **openstack** region. 
The name will be: `openstack_<region_name>` e.g.  `openstack_eu-de-1`

HAP pool logic is supposed to handle it smoothly.
WIP: https://github.com/kyma-project/kyma-environment-broker/pull/200/files
