### ISSUE TITLE
CCEE: Add new skr-sap-converged-cloud-integration-dev e2e periodic test

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#153]
**Description**

Main Epic: https://github.com/kyma-project/kyma/issues/13159

Create a periodic e2e test to check if **openstack** plan works as expected.

**AC**

- Add new test **skr-sap-converged-cloud-integration-dev** https://status.build.kyma-project.io/?job=**skr-**
- Prepare GA pipeline in the tools. Ask @PK to create new repository.

**Comment by MarekMichali** [comment]
We may need to use a `Workload Identity` to fetch secrets from `Secret Manager` that are needed by the tests.

**Comment by MarekMichali** [comment]
Values from secrets

KEB_HOST=keb-dev-credentials
KEB_CLIENT_ID=keb-dev-credentials
KEB_CLIENT_SECRET=keb-dev-credentials
KEB_GLOBALACCOUNT_ID=keb-dev-credentials
KCP_OIDC_CLIENT_ID=kcp-client-credentials
KCP_OIDC_CLIENT_SECRET=kcp-client-credentials
KCP_TECH_USER_LOGIN=kcp-client-credentials
KCP_TECH_USER_PASSWORD=kcp-client-credentials

GARDENER_KUBECONFIG= is taken from /gardener/kubeconfig

**Comment by MarekMichali** [comment]
GARDENER_KUBECONFIG  is mostly used in `machineTypeE2ETest` added here https://github.com/kyma-project/control-plane/issues/2497

**Comment by MarekMichali** [comment]
To get the cluster configuration, we use `kcp rt -c shoot -o json --cluster-config' instead of gardener kubeconfig.

**Comment by MarekMichali** [comment]
PR: https://github.com/kyma-project/kyma-environment-broker/pull/346

**Comment by MarekMichali** [comment]
Removal from Prow:
- https://github.com/kyma-project/test-infra/pull/9676
- https://github.com/kyma-project/test-infra/pull/9662
