### ISSUE TITLE
Refactor KEB docs

### ISSUE THREAD

**Issue by IwonaLanger** [kyma-project/kyma-environment-broker#26]
/**Description**

The KEB docs in the KCP repository must be reviewed, updated, deprecated, or rewritten for better maintenance. Some of the docs will be renumbered/renamed to arrange them into topic-based groups. **All the processes must be tested.**
*The docs that still need looking into have been renumbered*

**AC**

- [x] 1) Remove `01-01-overview.md` - it's nearly the same as the [README](`.components/kyma-environment-broker/README.md`) file. IL
- [X] 2) In `02-01-architecture.md`, adjust the diagram to the content guidelines. IL
- [X] 3) In `02-02-broker-endpoints.md`, add the link to `files/swagger/index.html`. ~~EDIT: the link added but doesn't work properly and needs checking DEV~~
- [x] 4) Compare `03-01-service-description.md` with the code and update the doc. Add updating parameters (per plan).  DEV @szwedm  https://github.com/kyma-project/kyma-environment-broker/pull/51
- [x] 5) In `03-03-runtime-operations.md`, remove the description of the steps from the doc; **the description must be provided in the code files**, and the doc should provide the link pointing there. Split the existing `main.go` file into 5 files, one for each of the operations. DEV; EDIT: Once the files with code are ready, the descriptions can be removed [maper]
- [X] 6) Confirm if `03-03-runtime-operations.md` is up-to-date with Framefrogs. No confirmation - they say it's Gophers' doc DEV
- [x] 7) Check if `contibutor/03-10-hyperscaler-account-pool.md` is up to date; in the future, the pools will be designed by plan in the format `plan-{region name}`. DEV (WW)
- [x] 8) `contibutor/01-10-authorization.md` needs updating - remove the outdated info (Hydra) and add the description of the scopes (mention IAS). DEV (@piotrmiskiewicz)
- [x] 9) In `contibutor/06-20-environments-cleanup.md`, add the instruction on how to trigger the job; compare with the doc in the internal documentation and update if necessary; EDIT: add the DETAILS section;
- [x] 10) All the jobs (`03-07-environments-cleanup.md`, ` 03-09-subaccount-cleanup-cronjob.md`, ` 03-15-trial-cleanup-cronjob.md`, ` 03-16-deprovision-retrigger-cronjob.md`) must be listed in a new doc providing short descriptions of what they do and links to their dedicated docs; mention that the jobs are not required for KEB to work (but their functions will not be performed if you don’t turn them on); the dedicated docs must all have the same structure. Q:What about ` 03-17-runtime-reconciler.md`? IL
- [X] 11) In `03-09-subaccount-cleanup-cronjob.md`, add the link to the resource definition. IL
- [x] 12) In `user/04-10-custom-oidc-configuration.md`, check if all the input parameters are listed; this doc should only list the parameters and point to specific docs describing them in detail. Add an e2e scenario. DEV
- [X] 13) In `03-14-broker-configuration-for-given-version-and-plan.md`, add a note that this doc will change as the configuration will be global per plan, not per version. DEV/ IL
- [X] 14) In `08-01-provisioning-kyma-environment.md`, improve formatting. IL +DEV
- [X] 15) Add a new doc (_"The future of KEB"_) with a diagram presenting the planned KEB architecture; link from and list the files which are to be deprecated. PK? + IL
- [ ] 16) Remove all references to Compass and Director. DEV 
- [X] 17) Once Reconciler is deprecated, also deprecate the following docs: `03-02-runtime-components.md`, `03-06-runtime-overrides.md`, `03-08-kyma-versions.md`,`03-10-orchestration.md`; for now, add a note about the planned deprecation. IL
- [ ] 18) Look through the code to see what hasn’t been documented in the docs yet. DEV; (EDIT: there'll be another ticket for Install KEB locally)
- [x] 19) Check all the links. IL
- [x] 20) Add the link-checker to the repository. IL
- ~~[ ] 21) Feed the KEB documentation to https://pages.github.tools.sap/kyma/#/.~~
- [x] 21) add the `user` and `contributor` folders (?) IL
- [x] 22) renumber the docs to arrange them in topic-related groups IL + DEV

**Comment by IwonaLanger** [comment]
The following docs need checking and updating:
- [ ] the main README file 
- [ ] 02-02-broker-endpoints.md
- [ ] 03-02-runtime-components.md
- [ ] 03-03-runtime-operations.md
- [ ] 03-04-hyperscaler-account-pool.md
- [ ] 03-05-authorization.md
- [ ] 03-06-runtime-overrides.md
- [ ] 03-08-kyma-versions.md
- [ ] 03-09-subaccount-cleanup-cronjob.md
- [ ] 03-10-orchestration.md
- [ ] 03-11-swagger.md
- [ ] 03-12-custom-oidc-configuration.md
- [ ] 03-13-custom-administrators.md
- [ ] 03-14-broker-configuration-for-given-version-and-plan.md
- [ ] 03-15-trial-cleanup-cronjob.md
- [ ] 03-16-deprovision-retrigger-cronjob.md)
- [ ] 03-17-runtime-reconciler.md
- [ ] 03-18-eu-access.md
- [ ] 08-01-provisioning-kyma-environment.md
- [ ] 08-02-deprovisioning-kyma-environment.md
- [ ] 08-03-operation-status.md
- [ ] 08-04-instance-details.md
- [ ] 08-05-orchestrate-kyma-upgrade.md
- [ ] 08-06-orchestration-status.md

**Comment by jaroslaw-pieszka** [comment]
03-15-trial-cleanup-cronjob.md - will be changed accordingly when @szwedm completes his current task.

**Comment by szwedm** [comment]
contributor/02-10-runtime-components.md 
https://github.com/kyma-project/kyma-environment-broker/issues/26

**Comment by ralikio** [comment]
main readme PR: https://github.com/kyma-project/kyma-environment-broker/pull/336

**Comment by ralikio** [comment]
Environments Cleanup Job: https://github.com/kyma-project/kyma-environment-broker/pull/385

**Comment by ralikio** [comment]
Operations Doc: https://github.com/kyma-project/kyma-environment-broker/pull/389
