### ISSUE TITLE
CCEE: Enable sap-converged-cloud plan only for internal usage in the cf-eu20

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#292]
**Description**

Main Epic: https://github.com/kyma-project/kyma/issues/13159
Continued in: https://github.tools.sap/kyma/backlog/issues/4704

**AC**
- [x] 1) Register sap-converged-cloud plan into cf-eu20. Available only for internals.

**Comment by jaroslaw-pieszka** [comment]
EU access related PRs (some of these):
https://github.com/kyma-project/control-plane/pull/2370
https://github.com/kyma-project/control-plane/pull/2413
