### ISSUE TITLE
Improve KEB unit tests workflow

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#293]
**Description**

The unit tests workflow invokes `make test`. The `pre-kyma-environment-broker` Prow job used for unit testing invokes `make release` and does more testing. Compare the two tests and implement the missing steps in the unit tests workflow. Also remove the `pre-kyma-environment-broker` Prow job.

**AC**

- [x] 1) Add missing steps in the unit tests workflow
- [x] 2) Remove `pre-kyma-environment-broker`  Prow job
- [x] 3) Document changes

_based on PK comment from 02.01.24_

- [x] 4) Execute unit tests only once
- [x] 5) Optimize storage container
- [x] 6) Remove not used make commands and refactor commands in Makefiles

**Comment by PK85** [comment]
Comment from @szwedm :
```
The same unit tests are executed twice. First, make runs unit tests without storage container, later, all tests are run again with storage container.

Storage container is created for every storage test, but it should be created once before all tests and cleaned after all tests.

make testing-with-database-network looks obsolete, probably should be removed.

Broker suite tests are a mess. It's hard to tell whether the tests are reflecting the real behaviour of broker processes, e.g. provisioning includes Provisioner, Reconciler, Infrastructure Manager, but deprovisioning tests include only Provisioner.
```

**Comment by jaroslaw-pieszka** [comment]
We use only a couple of targets on regular basis.

There are:

outdated targets, with improper logic or description
not used targets, not tested
mistery targets, nobody knows what are these for
AC:

all targets tested
all targets documented
all targets needed
Example:

```
.PHONY: module-template-push
module-template-push: ## Pushes the ModuleTemplate referencing the Image on MODULE_REGISTRY
	sh hack/local-template.sh
	kubectl apply -f template.yam
```
