### ISSUE TITLE
Move skr-test* and keb-auth into kyma-environment-broker repository

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#3]
**Description**
Remove our testing code from kyma repository. Keep tests itself.

**AC**
- [x] 0) Init kyma-environment-broker repository according to template (tide integration, labels etc...)
- [x] 1) Move those two guys into /testing directory under kyma-env-broker repository and switch in the test-infra to point to new place
- [x] 2) Add linting check
- [x] 3) Remove testing code from gophers from kyma/fast-integration
- [x] 4) Add documentation in new repo about tests

**Comment by MarekMichali** [comment]
Added KEB repo to test infra: https://github.com/kyma-project/test-infra/pull/8051

**Comment by MarekMichali** [comment]
Linting github action: https://github.com/kyma-project/kyma-environment-broker/pull/8

**Comment by MarekMichali** [comment]
KEB endpoints test: #7

**Comment by MarekMichali** [comment]
SKR test: https://github.com/kyma-project/kyma-environment-broker/pull/9
Switch in prow: https://github.com/kyma-project/test-infra

**Comment by MarekMichali** [comment]
Cleanup in Kyma repository: https://github.com/kyma-project/kyma/pull/17831

**Comment by MarekMichali** [comment]
Documentation: https://github.com/kyma-project/kyma-environment-broker/pull/10
