### ISSUE TITLE
MVP: Service binding for Kyma service instance

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#318]
Main epic: https://github.com/kyma-project/kyma-environment-broker/issues/284

**AC**
- [x] 0) KEB adjustments:
  - [x] a) Update schema for `aws` plan and make it bindable (see: https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md)
  - [x] b) implement service_binding endpoint which returns a simple json example
  - [x] c) add feature flag and enable only on DEV
  - [x] d) update ERS on staging
  - [x] e) check-in cockpit if you can create binding for Kyma Instance on AWS
- [x] 1) create a technical user in BTP and with BTP CLI create Kyma instance and Kyma binding THEN describe results (results here: https://github.com/orgs/kyma-project/projects/38/views/1?pane=issue&itemId=53475182)
- [x] 2) create a technical user in BTP with BTP CLI create "Service Manager/service-operator-access" instance and binding then with clientCredential create Kyma instance and Kyma binding THEN describe the result (results here: https://github.com/orgs/kyma-project/projects/38/views/1?pane=issue&itemId=53475182)

**Comment by piotrmiskiewicz** [comment]
BTP CLI does not have an option to create a binding for account/environments:

```
Examples:
    btp create services/binding --name my-binding-name --instance-name my-service-instance-name --subaccount my-subaccount
    btp create services/binding --name my-binding-name --service-instance my-service-instance-id --subaccount my-subaccount
    btp create services/binding --name my-binding-name --instance-name my-service-instance-name --parameters ~/Documents/parameters.json
    btp create services/binding --name my-binding-name --service-instance my-service-instance-id --parameters ~/Documents/parameters.json
```

**Comment by PK85** [comment]
Now we wait for the CIS team to present a solution to us and implement functionality.
