### ISSUE TITLE
Start throwing alerts when skr-test* are red

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#4]
**Description**
Right now we need to manually check the prow status page to see if those test works as expected. The idea is to just react when alerts happen.

**AC**
- [x] 1) prepare a place where we will monitor all gophers alerts, for example, new slack channel: kyma-gopher-private-gophers (this one will be monitored by dev on daily duty)
- [x] 2) check how to get alerts, only those related to skr-tests(we found that we can reuse alerts from prow, slack channel: kyma-ci-force)
  - [x] 2.1) Check if we need to use slack bot or not 
- [x] 3) Display failures and fixed runs in the nice way on brand new channel

**Comment by piotrmiskiewicz** [comment]
PRs: https://github.com/kyma-project/test-infra/pull/8107

**Comment by piotrmiskiewicz** [comment]
example of prometheus alerts configuration: https://github.tools.sap/kyma/management-plane-config/blob/main/resources/runtime-monitoring-integration/templates/rules.yaml#L2037
