### ISSUE TITLE
Improve KEB release process with publishing KEB chart

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#408]
**Description**

We need to change the way how things are promoted from the open-source KEB repository into internal environment. Right now it pulls every change from https://github.com/kyma-project/kyma-environment-broker/tree/main/resources/keb.

We want to trigger a promotion in the same way how we handle that for modules. That means we go to the internal repository and say promote e.g. 1.2.0 KEB version. Then it pulls a tag, takes whatever is needed and deploy. To achieve that we need to include chart into KEB releases. 

**AC**
- [x] 1) when releasing e.g. 1.2.0 KEB we need to include/publish a chart with the KEB image pointing to 1.2.0
- [x] 2) check the GA plugin for publishing charts (we need helm repository)
  - [x] 2.1) check this one: https://github.com/helm/chart-releaser-action, and usage:  https://github.com/gczuczy/multisources-refreshbug-chart/blob/main/.github/workflows/publish.yaml
- [x] 3) Update "release" documentation

**Comment by MarekMichali** [comment]
The proposed tools https://github.com/helm/chart-releaser-action can't add artefacts to an existing release, only create a new one.

**Comment by MarekMichali** [comment]
We decided that the bumps will have a special label and won't be added to the changelog.

**Comment by MarekMichali** [comment]
Feature: https://github.com/kyma-project/kyma-environment-broker/pull/499
Test infra changes to branch protection: https://github.com/kyma-project/test-infra/pull/10006
