### ISSUE TITLE
Introduce 2 CPU / 8 GiB RAM machine types for aws, gcp, azure, ccee

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#417]
**Description**

As with the modularization being complete the minimum footprint of a default Kyma "installation" is now severely reduced, and most users only use just a handful of modules, we could introduce new 2 CPU / 8 GiB RAM machine types for azure, aws, gcp and sap-converged-cloud plans:

- azure: Standard_D4s_v5
- aws: m5.large, m6i.large (make m6i as first element of enum, default: m6i.large) [See why create has only m5, and update m5 and m6i](https://github.com/kyma-project/kyma-environment-broker/blob/377cd14ea20dfb3c4476b0c9d40249c0123980c0/internal/broker/plans.go#L385))
- gcp: n2-standard-2
- sap-converged-cloud: g_c2_m8

**AC**
- [x] 0) check if in all our supported AWS regions m6i is available
- [x] 1) KEB allows provisioning and update of azure, aws, gcp, sap-converged-cloud runtimes with the new machine types
  - [x] 1.1) featureFlag to enable a change in the schema, set per environment
- [x] 2) those machine types are a new defaults for those plans (if not provided this one in use) 
- [x] 3) Kyma runtime documentation is up-to-date with the new machine types
- [x] 4) What's New post is published regarding the new machine types.
- [x] DC sync

**Comment by szwedm** [comment]
> * [ ]  0) check if in all our supported AWS regions m6i is available
According to [AWS Pricing Calculator](https://calculator.aws), m6i instance type is available in all supported regions.

**Comment by szwedm** [comment]
> * [ ]  1) KEB allows provisioning and update of azure, aws, gcp, sap-converged-cloud runtimes with the new machine types  
>   * [ ]  1.1) featureFlag to enable a change in the schema, set per environment

PR: https://github.com/kyma-project/kyma-environment-broker/pull/437

**Comment by szwedm** [comment]
> * [ ]  2) those machine types are a new defaults for those plans (if not provided this one in use)

PR: https://github.com/kyma-project/kyma-environment-broker/pull/444

**Comment by szwedm** [comment]
> * [ ]  3) Kyma runtime documentation is up-to-date with the new machine types
PR: https://github.com/kyma-project/kyma-environment-broker/pull/450

**Comment by szwedm** [comment]
Issue for removing the temporary feature flag:
https://github.com/kyma-project/kyma-environment-broker/issues/501
