### ISSUE TITLE
Redesign of metrics

### ISSUE THREAD

**Issue by ukff** [kyma-project/kyma-environment-broker#455]
**AC**

1) Tasks with relation to cleanup data feature: https://github.com/orgs/kyma-project/projects/38/views/1?pane=issue&itemId=51632175
- [x] Check how "cleanup data feature" will impact on current metrics counting
- [x] Implement changes needed to keep metrics working after "cleanup data feature" will be introduced
      - Make sure to take into consideration current not optimal SQL (GetOperationStats) and refactor it or delete it
      
2) SRE Dashboard:

- [x] add keb_operations_update_x_total metrics which works same as existing ones for provisioning/deprovisioning
```
keb_operations_update_failed_total gauge
keb_operations_update_in_progress_total gauge
keb_operations_update_succeeded_total
```
- [x] add upgrade and update operation type to keb_operation_result
- [x] add error label for failed operations in keb_operation_result
- [x] delete metrics 
```
compass_keb_upgrade_kyma_result
compass_keb_provisioning_result
compass_keb_deprovisioning_result

compass_keb_provisioning_step_result
compass_keb_deprovisioning_step_result
```

General:

- [x] limit number of exposed metrics to not reach promscrape.maxScrapeSize https://github.tools.sap/kyma/backlog/issues/4858
- [x] implement retention on operations metrics (7days)

Documentation:
- [x] Describe each metrics with business use case, type of it (prometheus type) and what is represented by value
- [x] Do metrics architecture diagram

**Comment by ebensom** [comment]
@ukff 
What about the current `operations_provisioning_*_total` and `operations_deprovisioning_*_total` counter metrics? 
These operations stats collector based metrics are useful and important to have besides the per-operation centric `keb_operation_result` metrics, as these could be easy indicators to track high level SLOs like ratio of succeeded provisioning/deprovisioning operations over specific time range.

**Comment by ebensom** [comment]
The propposed changes in https://sap-btp.slack.com/archives/CQF0V9075/p1710321960315799 looks good for SRE.
