### ISSUE TITLE
Remove the temporary feature flag for new machines types

### ISSUE THREAD

**Issue by szwedm** [kyma-project/kyma-environment-broker#501]
**Description**
PR https://github.com/kyma-project/kyma-environment-broker/pull/437 introduced new feature flag to enable support for new machines types in selected landscapes. Remove the feature flag when it becomes redundant:
https://github.com/kyma-project/kyma-environment-broker/blob/dc04e0d709a16b267e168f556d794d06cef6b8ea/internal/broker/broker.go#L44

**Reasons**

The feature flag will not be required when all landscapes will support new machines types.

**AC:**
- [ ] Machine types are available without toggling the feature flag.

**Comment by MarekMichali** [comment]
PR #675

**Comment by PK85** [comment]
@MarekMichali why this is in blocked column? If mistake move to done

**Comment by MarekMichali** [comment]
It's waiting for the values in mp-config to be removed.
