### ISSUE TITLE
Golinter - make timeout configurable from repo settings

### ISSUE THREAD

**Issue by szwedm** [kyma-project/kyma-environment-broker#582]
**Description:**
Linter timeout configuration for `make go-lint` command to use in GA. 

Usage example for 1m:
`golangci-lint run --timeout=1m`

**AC:**
- [ ] Variable is defined for repository
- [ ] GA uses the new variable

**Comment by KsaweryZietara** [comment]
Configuration variables are not available in workflows triggered by a pull request from a fork.
See [#44322](https://github.com/orgs/community/discussions/44322)
