### ISSUE TITLE
Free plan - kyma for 30 days, one provisioning in the given Global Account

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#593]
**Description**

From: 
- Right now we offer one Kyma instance in the Global Account for free (plan "free"). 

To: 
- 30 days after creationTimestamp KEB must deprovision Kyma instance, 
- Another "free" plan provisioing in this GA must fail (We allow to provision only once in given GA)

**AC**
- [x] 1) Functionality:
  - [x] 1.0) Extend InstanceArchived table with status of the provisioning (we will need that information to handle a case where user provisioned first time and KEB failed, we need to allow him to provision again) 
PR: https://github.com/kyma-project/kyma-environment-broker/pull/599
  - [x] 1.1) Functionality available under feature flag PR: https://github.com/kyma-project/kyma-environment-broker/pull/600
  - [x] 1.2) make 30 days as configuration for job and for KEB (days left calculation)
PRs: [job](https://github.com/kyma-project/kyma-environment-broker/blob/main/cmd/expirator/main.go#L30), [KEB](https://github.com/kyma-project/kyma-environment-broker/blob/main/internal/broker/broker.go#L46)
  - [x] 1.3) Show with metadata label under service instance how many days left for expiration
PRs: https://github.com/kyma-project/kyma-environment-broker/pull/633 [#5103](https://secret.repo/kyma/management-plane-config/pull/5103)
  - [x] 1.4) When time comes, deprovision Kyma instance 
PRs: https://github.com/kyma-project/kyma-environment-broker/pull/602 https://github.com/kyma-project/kyma-environment-broker/pull/607
  - [x] 1.5) Do not allow to provision Kyma with "free" plan in the Global Account (if free was already consumed) 
PR: https://github.com/kyma-project/kyma-environment-broker/pull/608
  - [x] 1.6) We need to make sure to be able to run skr-free-aws-integration-dev and argocd promotion tests for free plan (idea: whitelist GA ids + flag "freeOnlyOnce:" true/false)
  PR: [#5097](https://secret.repo/kyma/management-plane-config/pull/5097)
- [x] 2) Documentation: (@IwonaLanger)
  - [x] 2.1) help sap documentation [free plan description](https://help.sap.com/docs/btp/sap-business-technology-platform/available-plans-in-kyma-environment?version=Cloud#free) updated
     - [publication requested ](https://jira.tools.sap/browse/NGPDOC-4714) 
  - [x] 2.2) [RNs](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%20Runtime&Valid_as_Of=2024-04-17%3A2024-04-17&locale=en-US&version=Cloud)
  - [x] 2.3) [SAP Discovery Center](https://discovery-center.cloud.sap/protected/index.html#/serviceCatalog/kyma-runtime?commercialModel=cpea&region=all&tab=service_plan) 
     - [Data sheet for SAP BTP, Kyma runtime](https://help.sap.com/docs/help/01cd1c17c9304dc0ba6bc8650bdf3386/533df767c39b48c3ae08e2d226ead948.html?locale=en-US) updated
     - DC update [requested](https://jira.tools.sap/browse/NGPDOC-4709)
- [x] 3) Communication: (@marco-porru )
  - [x] 3.1) Send email to all users about a change and exact date of clusters removal   

**Links**
- check how we implemented expiration for trial clusters

**Comment by marco-porru** [comment]
Customer communication **NZA4694468** created
