### ISSUE TITLE
KEB release workflow adjustment for new promotion

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#637]
**Description**

The way that KEB is promoted has changed, and the release workflow needs to be adjusted accordingly. There is also an issue when the tests during release may fail but the bumps and tag are already created. This is problematic if the fix requires changes to the code, as the tag has already been created

**AC**

- [x] `Bump sec-scanners-config` and `Bump KEB Chart` are merged into one step
- [x] The bump is done after successfully running tests
- [x] `expirator` and `subaccount-sync` jobs are added to  `Wait for Prow jobs step`
- [x] `expirator` and `subaccount-sync` images are auto bumped
- [x] Update documentation

**Comment by MarekMichali** [comment]
PR: #634
