### ISSUE TITLE
Enhance `azure` and `azure_lite` plan with one new region: `australiaeast`

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#646]
**Description**

Add new region to the `azure` and `azure_lite` plans.

**Reason**

We will want to support new BTP region: Australia (Sydney) Microsoft Azure "cf-ap20"

**AC**
- [x] 1) Adjust schema for both plans, new region `australiaeast` and nice displayNames for all regions:
**from:**
```
	"region": {
			"enum": [
				"eastus",
				"centralus",
				"westus2",
				"uksouth",
				"northeurope",
				"westeurope",
				"japaneast",
				"southeastasia"
			],
			"minLength": 1,
			"type": "string"
		}
```
**to:**
```
"region": {
        "_enumDisplayName": {
        	"eastus": "eastus (US East, VA)",
        	"centralus": "centralus (US Central, IA)",
        	"westus2": "westus2  (US West, WA)",
        	"uksouth": "uksouth (UK South, London)",
        	"northeurope": "northeurope (Europe, Ireland)",
        	"westeurope": "westeurope (Europe, Netherlands)",
        	"japaneast": "japaneast (Japan, Tokyo)",
        	"southeastasia": "southeastasia (Asia Pacific, Singapore)",
        	"australiaeast": "australiaeast (Australia, Sydney)"
        },
	"enum": [
		"eastus",
		"centralus",
		"westus2",
		"uksouth",
		"northeurope",
		"westeurope",
		"japaneast",
		"southeastasia",
		"australiaeast"
	],
	"minLength": 1,
	"type": "string"
}
```
- [x] 2) Adjust documentation help.sap.com docs: [parameters](https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment#region*) and [regions](https://help.sap.com/docs/btp/sap-business-technology-platform/regions-for-kyma-environment?version=Cloud) PK comment: Kyma available in the new BTP region Australia (Sydney) Microsoft Azure "cf-ap20" and azure and azure_lite has new region: australiaeast
- [x] 3) [Release notes](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%20Runtime&locale=en-US&version=Cloud&Valid_as_Of=2024-04-23%3A2024-04-23&q=region) PK comment: Kyma available in the new BTP region Australia (Sydney) Microsoft Azure "cf-ap20" and azure and azure_lite has new region: australiaeast
- [x] 4) Register `azure` and `azure_lite` into "cf-ap20" in the CIS registry

**Comment by piotrmiskiewicz** [comment]
PR: https://github.com/kyma-project/kyma-environment-broker/pull/664/files

**Comment by IwonaLanger** [comment]
- The documentation updated and publication [requested](https://jira.tools.sap/browse/NGPDOC-4737)
  - The release note added and publication [requested](https://jira.tools.sap/browse/NGPDOC-4736)
