### ISSUE TITLE
Deploy `subaccount-sync` [betaEnabled] to higher landscapes

### ISSUE THREAD

**Issue by jaroslaw-pieszka** [kyma-project/kyma-environment-broker#693]
`subaccoount-sync` is deployed to DEV.

Deploy it to higher landscapes in controlled way using dry-run mode (updateResources setting) to rollout changes gradually.

AC:
- [x] on STAGE in dry-run mode, monitoring and alerts configured
- [x] on STAGE in fully operational mode
- [x] on PROD in dry-run mode, monitoring and alerts configured
- [x] on PROD in fully operational mode

**Comment by PK85** [comment]
Blocked, waiting for Plutono dashboards

**Comment by jaroslaw-pieszka** [comment]
Currently `subaccount-sync` is deployed on DEV only, monitoring and alerts are configured for DEV.

**Comment by jaroslaw-pieszka** [comment]
Enabling deployment on STAGE and PROD: https://github.tools.sap/kyma/management-plane-config/pull/5307

**Comment by jaroslaw-pieszka** [comment]
Reducing rate of calls for events: https://github.tools.sap/kyma/management-plane-config/pull/5310

On STAGE and PROD we experienced occasionally error status 429 when calling `events` endpoint, so to avoid hitting the limit we reduced  maximal number of call to 3 per 2s.

**Comment by jaroslaw-pieszka** [comment]
https://github.tools.sap/kyma/backlog/issues/5659
is blocking deployment of  https://github.com/kyma-project/kyma-environment-broker/pull/814
