### ISSUE TITLE
Fix goroutine leak

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma-environment-broker#709]
The number of goroutines is constantly growing. It looks like the AvS client (http with oauth) is created for every http call. It should be changed to use shared one. The initial AvS implementation was done this way, but there was a problem with token refreshing (see https://github.com/kyma-project/control-plane/pull/268/files).
AC:
 - no goroutines leak

In case of extracting AvShttp client to shared one - test the implementation for more than 24 h to check if it works fine (token refreshing etc.)

**Comment by MarekMichali** [comment]
One way to test it on dev without promoting it to stage is to add the `pr-deploy` label to the promotion PR. This will allow you to push the tested KEB version to dev with promotion to stage blocked. A good idea would be to do this on Friday and revert on Monday, so we get over 48 hours of testing without interfering with the normal KEB releases that happen during the week.

We should also create a custom KEB release from a fork for this testing scenario, by building and hosting the KEB chart there as we do upstream, without interfering with the upstream KEB release process. After successful testing, everything should be merged back to upstream and released there.

**Comment by MarekMichali** [comment]
The leak is somewhere in `AVS_Create_Internal_Eval_Step` during both provisioning and deprovisioning. This was confirmed by disabling this step. After disabling it, the goroutines count stopped growing.

**Comment by MarekMichali** [comment]
Creating `AVS external evaluation` is disabled on all environments, see https://github.com/kyma-project/kyma-environment-broker/pull/139

**Comment by MarekMichali** [comment]
We decide to leave this issue for now, as it only occurs on dev.
