### ISSUE TITLE
Reduce size of nodes to 2CPU/8GB RAM for trial and free plan

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#745]
**Description**

Reduce size of nodes to 2CPU/8GB RAM for trial and free plan.

**Reasons**

Cost reduction.

**AC**
- [x] 1) apply machine type change for free plan
  - [x] 1.1) deploy to dev and test
  - [x] 1.2) deploy to stage and test
  - [x] 1.3) deploy to prod and test
- [x] 2) apply machine type change for trial plan
  - [x] 2.1) deploy to dev and test
  - [x] 2.2) deploy to stage and test
  - [x] 2.3) deploy to prod and test
- [x] 3) Implement the mechanism with a feature flag
- [x] 4) Update help.sap docs  - [publication requested](https://jira.tools.sap/browse/NGPDOC-4891)
   - [x] [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment?locale=en-US&version=Cloud)
   - [x] [About the Trial Account](https://help.sap.com/docs/btp/sap-business-technology-platform/about-trial-account?locale=en-US&version=Cloud#loioc4fff0f58f90424f8e0af28975ac7f0f__section_trial_scope_limitations)
   - [x] disco 🥳  center (requested with this [Jira ticket](https://jira.tools.sap/browse/NGPDOC-4884))
- [x] 5) RNki - [Publication requested](https://jira.tools.sap/browse/NGPDOC-4890)

**Comment by MarekMichali** [comment]
The smaller machine type has also been added to Azure lite.
