### ISSUE TITLE
Support new sap-converged-cloud plan region: ap-au-1

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#793]
**AC**
- [x] 0) enhance sap-convereged-cloud plan witn possibility to display given ccee regions for given BTP regions. That means KEB must support mapping between a given BTP region e.g. "cf-eu21" and a list of CCEE regions per Landscape. Configuration must be applied here: https://github.tools.sap/kyma/management-plane-config/tree/main/argoenv/keb for all landscapes. https://github.com/kyma-project/kyma-environment-broker/pull/846
  - [x]  0.1) (converted to additional point by @ralikio) Prepare configuration syntax and define behaviour (with corner cases too) present to PO and team - https://github.com/kyma-project/kyma-environment-broker/pull/812, https://github.com/kyma-project/kyma-environment-broker/pull/818, https://github.com/kyma-project/kyma-environment-broker/pull/820
- [x] 1.1) For BTP region cf-ap10 the sap-converged-cloud plan catalog must return ap-au-1 region only:
```
"region": {
	"enum": [
     		"ap-au-1"
	],
	"minLength": 1,
	"type": "string"
}
```
- [x] 1.2) For BTP region cf-eu20 the sap-converged-cloud plan catalog must return eu-de-1 region only. This is already done, but has old implementation. Must be adjusted.
```
"region": {
	"enum": [
     		"eu-de-1"
	],
	"minLength": 1,
	"type": "string"
}
```			
- [ ] 2) Check if /catalog and /createInstance, /updateInstance validates region value - https://github.com/kyma-project/kyma-environment-broker/pull/886
- [x] 3) Adjust documentation - https://github.com/kyma-project/kyma-environment-broker/pull/859
- [x] 4) Documentation update:
   - [x] Prepare an [internal release note](https://help.sap.com/whats-new/f0d108472a9347d99053658d05ae23e2?Component=Kyma%20Runtime&locale=en-US&state=DRAFT&Valid_as_Of=2024-06-19%3A2024-06-19&q=AP)
   - [x] Update the internal Help Portal documentation:
      - [x] [Regions for the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/regions-for-kyma-environment?locale=en-US&state=DRAFT&version=Internal) 
      - [x] [Available Plans in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/available-plans-in-kyma-environment?locale=en-US&state=DRAFT&version=Internal#sap-converged-cloud)
      - [x] [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/provisioning-and-update-parameters-in-kyma-environment?locale=en-US&state=DRAFT&version=Internal#region*)
- [x] 5) ON DEV we have mapping: "cf-eu20-staging "<-> ["eu-de-1"]
- [x] 6) ON STAGE we have mapping: "cf-eu21 "<-> ["eu-de-1", "ap-au-1"]
- [x] 7) ON PROD we have mapping: "cf-eu20"<-> ["eu-de-1"] ; "cf-ap10"<-> ["ap-au-1"]

**Comment by ralikio** [comment]
I have create a simple test to check our options when using github.com/vrischmann/envconfig. Reading the lib's readme I have learnt bout possible parsing mapping as shown in https://github.com/kyma-project/kyma-environment-broker/pull/812. It would work for short lists, however, the longer the lists, the more troublesome its maintenance would be.

**Comment by ralikio** [comment]
We have decided to use functionality from whitelisted eu regions in KEB https://github.com/kyma-project/kyma-environment-broker/tree/main/internal/whitelist.

**Comment by ralikio** [comment]
A decision has been made with the team that when region from the path is not present then sap-converged-cloud plan is not returned in the schema.
