### ISSUE TITLE
BTP Kyma EU access implementation - register cf-ch20 region and drop whitelisting

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma-environment-broker#823]
Main ticket: https://github.tools.sap/kyma/backlog/issues/3115

**AC**
- [x] 1) KEB service catalog schema is registered in CIS and ERS in cf-ch20
- [x] 2)  Drop support for EU access allow list in KEB (if someone enables Kyma in the cf-ch20, cf-eu11 region then they just get it) - https://github.com/kyma-project/kyma-environment-broker/pull/888
- [x] 3) Docs update - ~~publication requested with this [Jira ticket](https://jira.tools.sap/browse/NGPDOC-4948)~~ published
  - [x] 3.1)  help sap docs update: mention cf-ch20: [Provisioning and Updating Parameters in the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment?version=Cloud)
  - [x] 3.2)  help sap docs update: remove section about whitelist and what to do if not allowed: [Regions for the Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform/regions-for-kyma-environment)
  - [x] 3.3) update opensource docs: [see]( https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/03-20-eu-access.md): https://github.com/kyma-project/kyma-environment-broker/pull/891
- [x] 4) [RN](https://help.sap.com/whats-new/cf0cb2cb149647329b5d02aa96303f56?Component=Kyma%20Runtime&Valid_as_Of=2024-07-10%3A2024-07-10&locale=en-US&version=Cloud) - ~~publication requested with this [Jira ticket](https://jira.tools.sap/browse/NGPDOC-4949)~~ published

**Link**

See what we already have in that topic:  https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/03-20-eu-access.md

**Comment by ralikio** [comment]
Waits for registration by @PK85

**Comment by PK85** [comment]
Assigned to me too, registering to envs

**Comment by PK85** [comment]
all request sent to dev, stage, prod
