### ISSUE TITLE
Remove Kyma upgrade capability

### ISSUE THREAD

**Issue by KsaweryZietara** [kyma-project/kyma-environment-broker#828]
**Description**
This ticket is an outcome of the [TASK](https://github.com/kyma-project/kyma-environment-broker/issues/536).

**AC**
- [x] 1) Remove `/upgrade/kyma` endpoint
https://github.com/kyma-project/kyma-environment-broker/pull/896
- [x] 2) Remove `KymaOrchestrationProcessingQueue` with it's steps
https://github.com/kyma-project/kyma-environment-broker/pull/900

Docu update:

- [x] [03-20-runtime-operations.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/03-20-runtime-operations.md)
- [x] [docs/contributor/02-50-orchestration.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-50-orchestration.md) - (SME @piotrmiskiewicz )
 - [x] [docs/contributor/02-70-orchestration-status.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-70-orchestration-status.md) (SME @piotrmiskiewicz )
 - [x] [kyma-environment-broker](https://github.tools.sap/kyma/documentation/blob/main/kyma-internal/support/on-call-guides/kcp/kyma-environment-broker/README.md)

**Comment by PK85** [comment]
@KsaweryZietara what will happen now if someone will upgrade Kyma clusters right now? I expect nothing should happen with success.

**Comment by KsaweryZietara** [comment]
Kyma upgrade works, but nothing will be done.
