### ISSUE TITLE
Refactor the docs after Kyma Runtime Reconciler removal

### ISSUE THREAD

**Issue by IwonaLanger** [kyma-project/kyma-environment-broker#837]
Revise and update or remove the docs:
User:
		- [docs/user/01-10-architecture.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/01-10-architecture.md) 
		- [docs/user/01-20-target-architecture.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/01-20-target-architecture.md) 
		- [docs/user/03-10-service-description.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/03-10-service-description.md)
		- [docs/user/03-20-runtime-operations.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/user/03-20-runtime-operations.md)
		
Contributor:
		- [docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-40-broker-configuration-for-given-version-and-plan.md) - 
		- [docs/contributor/02-50-orchestration.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-50-orchestration.md) 
		- [docs/contributor/02-60-orchestrate-kyma-upgrade.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-60-orchestrate-kyma-upgrade.md)
		- [docs/contributor/02-70-orchestration-status.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/02-70-orchestration-status.md)
                - [docs/contributor/07-10-runtime-reconciler.md](https://github.com/kyma-project/kyma-environment-broker/blob/main/docs/contributor/07-10-runtime-reconciler.md)

**Comment by PK85** [comment]
Duplicate, see: https://github.com/kyma-project/kyma-environment-broker/issues/536
