### ISSUE TITLE
Increase configurable runtime maximum worker node count

### ISSUE THREAD

**Issue by ebensom** [kyma-project/kyma-environment-broker#858]
**Description**

The maximum allowed `autoscalerMax` parameter should be increased to 300 for enterprise plans (aws, gcp, azure, sap-converged-cloud).
In the future, when multiple worker groups can be specified as parameters, KEB should validate if the sum of autocalerMax values of all worker groups don't exceed 300 

**Reasons**

Kyna runtime artificially limits cluster nodes scalability, however in practice, the practical maximum nodes a cluster can withstand is in the 150-300 range. 

**Attachments**

**Comment by PK85** [comment]
Right now we have autoscalerMax == 80

**Comment by MarekMichali** [comment]
Summary how it will look. Azure Lite wasn't changed.

|  | aws | gcp | azure | sap-converged-cloud | preview | azure lite |
|-----|-----|-----|-----|-----|-----|-----|
| autoscalerMax maximum | 300  | 300 | 300  | 300 | 300 | 40

@ebensom I've also included the preview plan in this change, unless it was specifically not mentioned in the issue and shouldn't be changed.

**Comment by ebensom** [comment]
@MarekMichali LGTM!

**Comment by PK85** [comment]
@IwonaLanger please adjust https://help.sap.com/docs/btp/sap-business-technology-platform/provisioning-and-update-parameters-in-kyma-environment#loioe2e13bfaa2f54a4fb179f0f1f840353a__section_Auto_Scaler_Max to what @MarekMichali mentioned here: https://github.com/kyma-project/kyma-environment-broker/issues/858#issuecomment-2188465641

**Comment by PK85** [comment]
all request sent to dev, stage, prod
