### ISSUE TITLE
KIM Integration - Phase 1 point 0: Prepare Structures

### ISSUE THREAD

**Issue by ralikio** [kyma-project/kyma-environment-broker#905]
Lay ground work for https://github.com/kyma-project/kyma-environment-broker/issues/791. Create structures that prepares work for implementing Runtime CR. Additionally, during analysis of https://github.com/kyma-project/kyma-environment-broker/issues/791 we discovered unnecessary indirect dependencies that are not used in our code.

**Acceptance Criteria** 

- [x] 1) Import structures - later on we can mitigate dependency
- [x] 2) Prepare test printing out yaml representation of created object 
- [x] 3) Fill structure with appropriate data, write down what we data we are missing now

**Comment by jaroslaw-pieszka** [comment]
Discussion with @piotrmiskiewicz concerning setting KymaResourceName:

- we need additional step which is called after `GenerateRuntimeIDStep` - when RuntimeID should have been established
- this step will calculate and store in operations `KymaResourceName`
- this step will defensively check if RuntimeID is set on entry, returning error if not.

**Comment by jaroslaw-pieszka** [comment]
Loose ends:
- [ ] we pass `cfg.Provisioner` to `CreateRuntimeResource` step. We need to handle this differently when Provisioner is no longer used, at least rename it, possibly merge with cfg.KimConfig as Parameter Object.

**Comment by jaroslaw-pieszka** [comment]
Next steps (short-term plans):
- [ ] complete logic creating shoot data for all plans
- [ ] test it mostly on step level
- [ ] create step checking Runtime CR status 
- [ ] tackle deprovisioning

**Comment by ralikio** [comment]
TODO:
- [ ] tests for `internal/provider/gcp.go` to be done after merging of #942

**Comment by jaroslaw-pieszka** [comment]
Next step
- [ ] Networking for Preview, Azure, GCP, AWS
- [ ] Networking for Trial (AWS, GCP, Azure), Sap Converged Cloud, Free, Azure Lite
