### ISSUE TITLE
Make instance update process timeout configurable.

### ISSUE THREAD

**Issue by ebensom** [kyma-project/kyma-environment-broker#981]
**Description**

The hardcoded [40 minutes timeout](https://github.com/kyma-project/kyma-environment-broker/blob/005d53b0c752f3b81547381072f58913725d31e0/cmd/broker/update.go#L39) for the update process is not sufficient, as with machine image being updated, the update can take considerably more to process. 
Introduce configuration for this timeout value in the KEB code and helm chart, with default having 120m (2 hours).
SRE would like to specify overrides for this configuration per each KCP environment. 

**Expected result**

KEB update operations have configurable timeout. 

**Actual result**

KEB update operations often ends with failed due to 40 minutes timeout. 

**Steps to reproduce**

**Troubleshooting**

**Comment by MarekMichali** [comment]
It will be released with KEB 1.10.15
